Data Structures/Controllers/DictionaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Data_Structures.Controllers
{
    public class DictionaryController : Controller
    {
        // GET: Dictionary
        public ActionResult Index()
        {
            return View();
        }
    }
}

Data Structures/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Data_Structures.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Data Structures/Controllers/QueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Data_Structures.Controllers
{
    public class QueueController : Controller
    {
        // GET: Queue
        public ActionResult Index()
        {
            return View();
        }
    }
}

Data Structures/Controllers/StackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Data_Structures.Controllers
{
    public class StackController : Controller
    {
        // GET: Stack
        public ActionResult Index()
        {
            return View();
        }
    }
}

Data Structures/Views/Dictionary/Index.cshtml
<!--Dictionary Index-->
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    Dictionary Index I no longer need this change
</div>

Data Structures/Views/Home/Index.cshtml
<!--Home Index-->
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Data Structures/Views/Queue/Index.cshtml
<!--Queue Index-->
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<div>
    Queue Index
</div>

Data Structures/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/myStyles.css" rel="stylesheet" type="text/css"/> <!--My Style Sheet File-->
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/Scripts/myScripts.js"></script> <!--My Scripts File-->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Stack")">Stack</a></li>
                    <li><a href="@Url.Action("Index", "Dictionary")">Dictionary</a></li>
                    <li><a href="@Url.Action("Index", "Queue")">Queue</a></li>
                </ul>
            </div>
        </div>
    </div>

    @*<div>
        <img src="~/Graphics/NET_MVC.jpg" style="width:100%"/>
    </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Data Structures/Views/Stack/Index.cshtml
<!--Stack Index-->
@{
    ViewBag.Title = "Index";
}
<style>
    body {
        font-family: "Lato", sans-serif;
    }

    .sidenav {
        height: 100%;
        width: 160px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 75px;
    }

        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 25px;
            color: #818181;
            display: block;
        }

            .sidenav a:hover {
                color: #f1f1f1;
            }

    .main {
        margin-left: 160px; /* Same as the width of the sidenav */
        font-size: 28px; /* Increased text to enable scrolling */
        padding: 0px 10px;
    }
</style>

<h2>Index</h2>


<div class="sidenav">
    <a href="#">
        1. Add one time to Stack
    </a>
    <a href="#services">
        2. Add Huge List of Items to Stack
    </a>
    <a href="#clients">
        3. Display Stack
    </a>
    <a href="#contact">
        4. Delete from Stack
    </a>
    <a href="#contact">
        5. Clear Stack
    </a>
    <a href="#contact">
        6. Search Stack
    </a>
    <a href="#contact">
        7. Return to Main Menu
    </a>
</div>